# Generated by Django 3.2.14 on 2022-08-04 04:37

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bedrooms',
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=2, validators=[listings.models.validate_nonzero]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedroom',
            field=models.IntegerField(validators=[listings.models.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='garage',
            field=models.IntegerField(validators=[listings.models.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[listings.models.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(validators=[listings.models.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(validators=[listings.models.validate_nonzero]),
        ),
    ]
